name: rishi.app PR Code Review via Open AI

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  authorization:
    runs-on: ubuntu-latest
    outputs:
      authorized: ${{ steps.check_author.outputs.authorized }}
    steps:
      - name: Check if the author is the pull request creator
        id: check_author
        run: |
          if [[ "${{ github.event.pull_request.user.login }}" == "${{ github.event.pull_request.user.login }}" ]]; then
            echo "true"  # Output 'true' if authorized
          else
            echo "false" # Output 'false' if not authorized
          fi

  test:
    needs: authorization
    runs-on: ubuntu-latest
    if: needs.authorization.outputs.authorized == 'true'
    # if: github.repository == 'rishi-raj-jain/next.rishi.app'
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{github.event.pull_request.head.repo.full_name}}
          ref: ${{github.event.pull_request.head.ref}}
          submodules: false

      - uses: unsafecoerce/chatgpt-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          action: review
          review_comment_lgtm: true
          path_filters: '**/*'
      - uses: unsafecoerce/chatgpt-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          action: score
